# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.studies_api import StudiesApi


class TestStudiesApi(unittest.TestCase):
    """StudiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StudiesApi()

    def tearDown(self) -> None:
        pass

    def test_list_studies(self) -> None:
        """Test case for list_studies

        Studies
        """
        pass


if __name__ == '__main__':
    unittest.main()
